### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by landsman** [samtimalsina/matter#19]
Hi,

I was install theme via composer, run `npm install` and `npm run build` but there is some error during building:

```
$ npm run build

> drupal-matter@0.0.1 build /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter
> mkdirp build && webpack --progress --colors

[1] Hash: 018190fd1730e3cf94c0a3f8c0fc17019279c76b                                     
Version: webpack 2.7.0
Child js-components:
    Hash: 018190fd1730e3cf94c0
    Time: 17832ms
        Asset     Size  Chunks             Chunk Names
    matter.js  4.85 kB       0  [emitted]  main
       [0] ./app/matter.js 2.16 kB {0} [built]
Child css:
    Hash: a3f8c0fc17019279c76b
    Time: 18598ms
               Asset     Size  Chunks             Chunk Names
    matter.css-entry  4.49 kB       0  [emitted]  matter
       [0] ./scss/matter.scss 1.68 kB {0} [built] [failed] [1 error]
       [1] multi ./scss/matter.scss 28 bytes {0} [built]
       [2] ./~/css-loader?{"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/animation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/auto-init","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/base","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/button","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/card","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/checkbox","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/dialog","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/drawer","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/elevation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/fab","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/form-field","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/grid-list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/icon-toggle","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/layout-grid","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/menu","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/radio","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/ripple","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/rtl","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/select","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/selection-control","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/snackbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/switch","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/tabs","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/textfield","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/theme","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/toolbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/typography"]}!./scss/matter.scss 425 bytes [built] [failed] [1 error]
       [3] ./~/style-loader/addStyles.js 9.15 kB [built]
       [4] ./~/style-loader/fixUrls.js 3.01 kB [built]
    
    ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/animation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/auto-init","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/base","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/button","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/card","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/checkbox","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/dialog","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/drawer","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/elevation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/fab","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/form-field","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/grid-list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/icon-toggle","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/layout-grid","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/menu","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/radio","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/ripple","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/rtl","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/select","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/selection-control","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/snackbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/switch","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/tabs","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/textfield","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/theme","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/toolbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/typography"]}!./scss/matter.scss
    Module build failed: 
    $mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                              ^
          Undefined variable: "$mdc-animation-standard-curve-timing-function".
          in /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/@material/elevation/_variables.scss (line 122, column 44)
     @ ./scss/matter.scss 4:14-192
     @ multi ./scss/matter.scss
    
    ERROR in ./scss/matter.scss
    Module build failed: ModuleBuildError: Module build failed: 
    $mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                              ^
          Undefined variable: "$mdc-animation-standard-curve-timing-function".
          in /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/@material/elevation/_variables.scss (line 122, column 44)
        at runLoaders (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/webpack/lib/NormalModule.js:192:19)
        at /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/sass-loader/lib/loader.js:55:13)
        at Object.<anonymous> (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/async/dist/async.js:2257:31)
        at Object.callback (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/async/dist/async.js:958:16)
        at options.error (/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/node-sass/lib/index.js:294:32)
    Child extract-text-webpack-plugin:
           [0] ./~/css-loader?{"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/animation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/auto-init","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/base","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/button","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/card","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/checkbox","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/dialog","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/drawer","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/elevation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/fab","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/form-field","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/grid-list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/icon-toggle","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/layout-grid","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/menu","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/radio","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/ripple","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/rtl","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/select","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/selection-control","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/snackbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/switch","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/tabs","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/textfield","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/theme","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/toolbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/typography"]}!./scss/matter.scss 425 bytes {0} [built] [failed] [1 error]
        
        ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/animation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/auto-init","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/base","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/button","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/card","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/checkbox","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/dialog","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/drawer","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/elevation","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/fab","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/form-field","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/grid-list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/icon-toggle","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/layout-grid","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/list","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/menu","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/radio","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/ripple","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/rtl","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/select","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/selection-control","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/snackbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/switch","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/tabs","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/textfield","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/theme","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/toolbar","/Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/~/@material/typography"]}!./scss/matter.scss
        Module build failed: 
        $mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                                  ^
              Undefined variable: "$mdc-animation-standard-curve-timing-function".
              in /Users/michal.landsman/localhost/marianne-thunder/docroot/themes/contrib/matter/node_modules/@material/elevation/_variables.scss (line 122, column 44)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! drupal-matter@0.0.1 build: `mkdirp build && webpack --progress --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the drupal-matter@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michal.landsman/.npm/_logs/2018-01-09T19_48_12_410Z-debug.log
```

what do you suggest?

**Comment by samtimalsina** [comment]
Let me take a look at this and get back to you.

**Comment by samtimalsina** [comment]
Try rebuilding node-sass like this:

```
npm rebuild node-sass --force
```

By the way, you don't have to build the styles unless you are planning to contribute back to the theme or alter the theme in some way. In the latter case, you should create a child theme to override the main theme. 

Assets have already been compiled in /css and /js, so you should be able to use the theme right out of the box.
